name: LifeMoney
version: '1.2.0'
main: net.azisaba.lifemoney.LifeMoney
api-version: '1.21'
authors: [ MCLove32 ]
description: LifeNewPvEの通貨の中枢。

depend:
  - Vault
softdepend:
  - MythicMobs

commands:
  lifemoneygive:
    permission: lifemoney.command.lifemoneygive
    aliases:
      - lmg
      - lmgive
  lifemoneyshow:
    permission: lifemoney.command.lifemoneyshow
    aliases:
      - lms
      - lmshow
  lifemoneyforcegive:
    permission: lifemoney.command.lifemoneyforcegive
    aliases:
      - lmfg
      - lmfgive